version: "2.2"

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Mysql@123
    volumes:
      - "./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
  mysql_test:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: Mysql@123
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - "./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"